# Generated by Django 4.2.16 on 2024-11-11 18:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_data', models.DateTimeField(default=datetime.datetime(2024, 11, 11, 18, 45, 29, 613247), null=None, verbose_name='Дата')),
                ('doc_number', models.SmallIntegerField(unique_for_year='doc_data', verbose_name='Номер')),
                ('percent', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Процент выработки')),
                ('description', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150, verbose_name='ФИО')),
                ('hired', models.DateField(verbose_name='Устроен')),
                ('dismissed', models.BooleanField(default=False, verbose_name='Уволен')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('quota', models.PositiveSmallIntegerField(verbose_name='Норма выработки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('percent', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Процент от нормы')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.createdproducts')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='performance.product', verbose_name='Изделие')),
            ],
        ),
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working', models.TimeField(default=datetime.time(12, 0), verbose_name='Отработанное время')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.createdproducts')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='performance.employee', verbose_name='Сотрудник')),
            ],
        ),
    ]
