# Generated by Django 4.2.16 on 2024-11-12 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brigade',
            options={'ordering': ['doc'], 'verbose_name': 'Бригада', 'verbose_name_plural': 'Бригады'},
        ),
        migrations.AlterModelOptions(
            name='createdproducts',
            options={'ordering': ['doc_data'], 'verbose_name': 'Документ выработки', 'verbose_name_plural': 'Документы выработки'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['fullname'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Изделие', 'verbose_name_plural': 'Изделия'},
        ),
        migrations.AlterModelOptions(
            name='production',
            options={'ordering': ['doc'], 'verbose_name': 'Выработка', 'verbose_name_plural': 'Выработки'},
        ),
        migrations.AlterField(
            model_name='createdproducts',
            name='doc_data',
            field=models.DateField(default=datetime.datetime(2024, 11, 12, 19, 10, 52, 872951, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='createdproducts',
            name='doc_number',
            field=models.PositiveSmallIntegerField(unique_for_year='doc_data', verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dismissed',
            field=models.BooleanField(choices=[(True, 'Уволен'), (False, 'Сотрудник')], default=False, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hired',
            field=models.DateField(default=datetime.datetime(2024, 11, 12, 19, 10, 52, 875324, tzinfo=datetime.timezone.utc), verbose_name='Устроен'),
        ),
    ]
